# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'medlink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
     pod 'Firebase/Core'
     pod 'Firebase/Auth'
     pod 'Firebase/Firestore'
     pod 'Firebase/Storage'
     pod 'FirebaseDatabase'
     pod 'Alamofire'
   
  # Pods for medlink

  target 'medlinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
